### ISSUE TITLE
Log errors with source line information instead of raising exceptions

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-diagram#223]
When users mistype for example an output format

```
[plantuml, deployment, typo]
----
----
```

this will throw an exception like this:

```
raise "#{self.class.name} does not support output format #{format}" unless generator_info
````

leaving the user (and an IDE) without a line number. 

When errors happen inside Asciidoctor, these are logged using something like the following

```
logger.error message_with_context %(include #{target_type} not readable: #{inc_path}), source_location: cursor
```

and the processing continues (probably after skipping the problematic block). After the processing, all problems are available in the log, and the IDE can point the user to the problematic line. 

I would hope that Asciidoctor Diagram would pick up a similar error handling like Asciidoctor, to support IDEs (like the IntelliJ plugin) to show the error with a line number. This references an issue raised by a user https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/247

Thanks!

**Comment by pepijnve** [comment]
That makes sense. @mojavelinux any guidance on what the appropriate behaviour is for extensions when encountering processing errors? Can I just return `nil` for instance?

**Comment by pepijnve** [comment]
@ahus1 could you give 464add8 a try?

**Comment by ahus1** [comment]
The source location will only be set if sourcemap is se to true. I tried the following 

```
require 'asciidoctor'
require 'asciidoctor-diagram'

Asciidoctor.convert_file 'test.adoc', sourcemap: true
```

and then found that the source location was present in the error message. 

But the location is the location of the parent, and the parent could be the previous heading that is several lines (and paragraphs) above. Therefore it will not show the accurate position to the user. 

I see that asciidoctor usually gets the cursor position of the reader when it outputs error messages; this doesn't depend on the sourcemap attribute. 

If Asciidoctor Diagram doesn't have access to the cursor position, maybe it is better to throw an exception and letting asciidoctor log the error with the cursor's line number?

**Comment by pepijnve** [comment]
🤔 I think we need input from @mojavelinux on this one. AFAIK there's no well defined error handling model for extensions. If the an extension raises an exception the entire processing of the asciidoc file halts.

From the extension processing method I can't get the actual current line indeed. Might be possible for blocks, but definitely not for block macros.

**Comment by mojavelinux** [comment]
> If the an extension raises an exception the entire processing of the asciidoc file halts.

That's correct. Unless that's what you really want, the more correct thing to do is to log an error.

> From the extension processing method I can't get the actual current line indeed.

This is indeed a shortcoming of the reader model, which doesn't maintain a reader hierarchy. However, you can get the line number information from the parent reader.

Here's an example:

```rb
Asciidoctor::Extensions.register do
  block_macro :foobar do
    self.class.include Asciidoctor::Logging
    process do |parent, target, attrs|
      logger.error message_with_context 'you are here', source_location: parent.reader.cursor_at_prev_line
      nil
    end
  end
end
```

> what the appropriate behaviour is for extensions when encountering processing errors? Can I just return nil for instance?

As shown above, log an error (or warning), then return nil.

**Comment by pepijnve** [comment]
@mojavelinux `asciidoctor/parser.rb:505` sets a mark on the reader. I think I could (ab)use that to get the location of the start of the block. Is it safe to assume that mark will stay there or am I counting too much on an implementation detail?

**Comment by mojavelinux** [comment]
When you're in a block processor, you can rely on mark to be where the block started since that's the purpose of the mark in this context. So yes, I'd say so.

**Comment by pepijnve** [comment]
Excellent. I'll use that to capture the location then.

**Comment by mojavelinux** [comment]
:+1:

**Comment by pepijnve** [comment]
Does 04551d1 look about right? `parent.reader...` doesn't work since `AbstractNode` doesn't have a reference to the `Reader`. The `Document` does.
Are there any pitfalls here related to tables, includes, etc?

**Comment by mojavelinux** [comment]
Yes, that's correct. (parent.reader works if parent is a Document, but not if it's an AbtractBlock). But parent.document.reader gets you to the same place.

**Comment by pepijnve** [comment]
@ahus1 should be fixed in 1.5.17. Feel free to reopen if there are still problems.

**Comment by ahus1** [comment]
@pepijnve - the code change looks promising. I tried to test it on JRuby, but bundler doesn't find a Java version yet (only 1.5.16). Should I wait a little bit longer? Should I flush any caches? 

```
$ bundle update --full-index
Could not find gem 'asciidoctor-diagram (~> 1.5, >= 1.5.17) java' in any of the
gem sources listed in your Gemfile.
```

**Comment by pepijnve** [comment]
Not sure why it’s not showing up. Seems to be published correctly according to https://rubygems.org/gems/asciidoctor-diagram

**Comment by ahus1** [comment]
I'll give it a bit more time and try again later.

**Comment by ahus1** [comment]
I still have the problem to test it directly with jruby and bundler, but I works with the latest release of asciidoctorj-diagram; therefore I'll try no further.

I successfully tested that the new versions renders an error message on the console, and that the next version of the plugin will highlight the error in the IDE. It will place the error in the line with the first "----", but that's fine for me.
